data:
  data_directory: ./SilentWearData
  subject_id: S01
paths:
  processed: data_raw_and_filt
  win_and_feats: wins_and_features
conditions:
  silent: silent
  vocalized: vocalized
window:
  window_size_s: 1.4
feature_extraction:
  manual_feature_extraction: false
  num_subwindows: 7
save_wins_and_feats: true
