model:
  kind: dl
  name: speechnet
  kwargs:
    p_dropout: 0.5
    global_pool: avg

    blocks_config:
      - out_channels: 8
        kernel: [1, 4]
        pool:   [1, 8]

      - out_channels: 16
        kernel: [1, 16]
        pool:   [1, 4]

      - out_channels: 16
        kernel: [1, 8]
        pool:   [1, 4]

      - out_channels: 32
        kernel: [7, 1]
        pool:   [1, 1]

      - out_channels: 32
        kernel: [7, 1]
        pool:   [1, 1]

    train_cfg:
        num_epochs : 100
        optimizer_cfg : {"name": "adam", "lr": 1e-3}
        "scheduler": {"factor": 0.1,"mode": "min","name": "ReduceLROnPlateau","patience": 2}
        early_stop_patience : 10
        lr : 1e-3
        weight_decay : 1e-4



        